name: Build Website

# We don't want pushes (or PRs) to gh-pages to kick anything off
on:
  push:
    branches:
      - master
      - '[0-9]+.[0-9]+.x'
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
  pull_request:

jobs:
  Build:
    name: Build with Sphinx
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: python -m pip install -r ci/build_requirements.txt

    - name: Build site
      run: |
        pushd site
        make html O=-W
        popd

    # Need to do separately and remove these extra license files that get dumped into
    # the build and cause warnings.
    - name: Check links
      run: |
        pushd site
        find build/html/_static -name LICENSE.md -delete
        make linkcheck
        popd

    - name: Upload site as artifact
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/upload-artifact@v2
      with:
        name: build-site
        path: site/build/html

    - name: Upload to GitHub Pages
      if: ${{ github.event_name != 'pull_request' }}
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/build/html
        exclude_assets: '.buildinfo,_static/jquery-*.js,_static/underscore-*.js'
        keep_files: false
        full_commit_message: Deploy to GitHub Pages
